### PR TITLE
Switch to esbuild-jest

### PR DESCRIPTION
**Pull request by amacneil**
Anyone care to figure out why this test fails with `esbuild-jest` (locally and in CI)?

Note the line number is wrong too.

### CODE REVIEW

**Comment by jtbandes** [comment]
esbuild doesn't add `"use strict"` to the top of the file like babel does: https://github.com/evanw/esbuild/issues/422#issuecomment-739740602 https://babeljs.io/docs/en/babel-plugin-transform-strict-mode

It'd be nice to have a way to always enable strict mode for all our code, but it looks like esbuild-jest may not expose the ability to set a `banner` as recommended in that thread. Maybe we need to propose a change to esbuild-jest.

**Comment by amacneil** [comment]
Does tsc emit “use strict”? I don’t remember seeing it do that.

**Comment by amacneil** [comment]
Looks like `tsc` adds `"use strict"` to the cjs build but not the esm build (and it appears that [strict mode is implicitly enabled in javascript when using esm](https://ponyfoo.com/articles/es6-modules-in-depth#strict-mode)).

That seems like a good argument for us enabling `"use strict"` everywhere we use `esbuild-jest` (including template repo).

**Comment by amacneil** [comment]
Going to switch back to `ts-jest` in our default repo configuration instead:

https://github.com/foxglove/template-typescript/pull/35

**Pull request closed without merging**
