### PR TITLE
Change README to use @foxglove/rosbag

### PR DESCRIPTION
**Pull request by defunctzombie**

### CODE REVIEW

**Comment by defunctzombie** [comment]
@amacneil blocked on this being published to npm (ideally with automatic publish bot)

**Comment by amacneil** [comment]
Publishing is set up as soon as you’re ready to tag a version

**Comment by defunctzombie** [comment]
@amacneil Whats the workflow we use for that since I need to bump the version in package.json. Should I be using your version bump action? Or do I make a PR that bumps the version? Branch?

**Comment by amacneil** [comment]
Just push the tag directly to main. 

E.g. https://github.com/foxglove/electron-socket#releasing

Should add this to readme. 

Pushing the specific tag is safer than `git push —tags`

**Comment by defunctzombie** [comment]
How does that work for protected branches?

**Comment by amacneil** [comment]
You need to be a repo admin to bypass branch protection. Or you can make the version bump in a PR and then tag it and push the tag after you merge. Pushing the tag is the thing that triggers npm publish.

**Pull request merged**
